---
- name: "Disable persistent directive when configured"
  template:
    src: "apt-daily.timer.conf.j2"
    dest: "/etc/systemd/system/apt-daily.timer.d/apt-daily.timer.conf"
  when: "{{ server_apt_disable_persistent_directive }}"
